name: Compile Go Program for Android ARMv7

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20' # Specify your desired Go version

    - name: Set up environment variables for cross-compilation
      run: |
        echo "GOOS=linux" >> $GITHUB_ENV
        echo "GOARCH=arm" >> $GITHUB_ENV
        echo "GOARM=7" >> $GITHUB_ENV

    - name: Compile Go program for Android ARMv7
      run: go build -o output_binary ./main.go

    - name: Upload compiled binary
      uses: actions/upload-artifact@v3
      with:
        name: android-armv7-binary
        path: output_binary
