name: release binaries


# .github/workflows/release.yaml

on:

  workflow_dispatch:
  
permissions:
    contents: write
    packages: write

jobs:


  release-linux-amd64:
    name: release android
    runs-on: ubuntu-latest
    steps:

    - name: Export CGO_ENABLED dynamically
      run: echo "CGO_ENABLED=1" >> $GITHUB_ENV 
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: android
        goarch: arm
        goarm: 7
        
        

